//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class BaseChatViewModel;
@protocol MessageNodeViewDelegate <NSObject>

@end

@interface BaseChatCellView : UIView
{
    id <MessageNodeViewDelegate> m_delegate;
    BaseChatViewModel *m_viewModel;
    struct CGSize m_layoutSize;
    _Bool m_isLayouting;
}

- (_Bool)canBeReused;
@property(nonatomic) __weak id <MessageNodeViewDelegate> delegate; // @synthesize delegate=m_delegate;
- (id)initWithViewModel:(id)arg1;
@property(nonatomic) _Bool isLayouting; // @synthesize isLayouting=m_isLayouting;
- (void)layoutFinished;
- (void)layoutInternal;
- (void)layoutSubviews;
- (void)onAppear;
- (void)onDisappear;
- (void)prepareForReuse;
- (void)resetLayoutCache;
- (void)setViewModel:(id)arg1;
- (_Bool)shouldLayoutIfNeeded;
@property(readonly, nonatomic) BaseChatViewModel *viewModel; // @synthesize viewModel=m_viewModel;

@end

