//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseChatCellView.h"

@class BaseMessageViewModel, NSArray, NSString, UIImageView, UIView;

@interface BaseMessageCellView : BaseChatCellView
{
    NSArray *m_arrMenuItems;
    UIView *m_contentView;
    UIImageView *m_sendOKView;
    _Bool m_touchEnded;
    _Bool m_bDisableAllOperation;
    _Bool m_bIsLongPressHandled;
    _Bool m_isConverting3dTouchToLongPress;
}

- (void)LongPressEvents;
- (id)accessibilityLabel;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)addSendOKView;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPeek;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)canShowDeleteMenuItem;
- (_Bool)canShowFavoriteMenuItem;
- (_Bool)canShowForwardMenuItem;
- (_Bool)canShowMoreMenuItem;
- (_Bool)canShowRevokeMsgMenuItem;
- (_Bool)canShowSendTo3rdApp;
- (_Bool)canShowSendToDevices;
- (_Bool)canShowShareMsgToOpenSDKMenuItem;
- (double)contentViewCenterY;
- (void)dealloc;
- (id)deleteMenuItem;
- (id)displayViewForImageBrowser;
- (void)doFavorite;
- (void)doForward;
- (id)favoriteMenuItem;
@property(readonly, nonatomic) __weak UIView *forceTouchShakeView;
- (id)forwardMenuItem;
- (void)handleMenuControllerWillHideMenuNotification:(id)arg1;
- (void)hideUIStatus;
@property(nonatomic) _Bool highlighted;
- (_Bool)isTouchInView:(id)arg1;
- (void)layoutContentView;
- (void)layoutFinished;
- (void)layoutInternal;
- (id)moreMenuItem;
- (void)onDelete:(id)arg1;
- (void)onFavorite:(id)arg1;
- (void)onForward:(id)arg1;
- (void)onLongTouch;
- (void)onMore:(id)arg1;
- (void)onRestore:(id)arg1;
- (void)onRevokeMsg:(id)arg1;
- (void)onShareMsgToOpenSDK:(id)arg1;
- (void)onTouchCancel;
- (void)onTouchDown;
- (void)onTouchDownRepeat;
- (void)onTouchEnded;
- (void)onTouchUpInside;
- (id)operationMenuItems;
- (struct CGRect)previewingSourceRectForLocation:(struct CGPoint)arg1 inCoordinateView:(id)arg2;
- (id)restoreMenuItem;
- (id)revokeMsgMenuItem;
- (void)setDisableAllOperation;
- (id)shareMsgToOpenSDKMenuItem;
- (void)showOperationMenu;
- (struct CGRect)showRectForMenuController;
- (void)showUIStatus;
- (struct CGRect)targetRectForMenuController;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)triggerLongPressFor3DTouchAtLocation:(struct CGPoint)arg1 inCoordinateView:(id)arg2;
- (void)updateNodeStatus;
- (void)updateStatus;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) BaseMessageViewModel *viewModel; // @dynamic viewModel;

@end

