//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIResponder.h"

@class CAppObserverCenter, CAppViewControllerManager, CMainControll, MMSMStartViewController, MMServiceCenter, MMUIWindow, NSRecursiveLock, NSString, ResourceInfo, ResourceMonitor, UILabel, UIWindow, VoIPTokenRetriveObject;

@interface MicroMessengerAppDelegate : MMUIResponder
{
    CAppObserverCenter *m_appObserverCenter;
    CMainControll *m_mainController;
    MMServiceCenter *m_serviceCenter;
    CAppViewControllerManager *m_appViewControllerMgr;
    NSString *m_nsToken;
    NSString *m_nsSound;
    NSString *m_nsVoipSound;
    unsigned int m_uLastTimeResignActive;
    unsigned int m_uInitViewType;
    long long m_tTotalRunningTime;
    long long m_tLastActiveTime;
    long long m_appVerCompareWithLastRun;
    _Bool m_isActive;
    UILabel *m_changeValueLabel;
    UILabel *m_resourceLabel;
    MMUIWindow *m_resourceWindow;
    ResourceInfo *m_lastResourceInfo;
    ResourceMonitor *m_resourceMonitor;
    NSRecursiveLock *mActiveLock;
    _Bool mInBackground;
    _Bool mInBackGroundFetch;
    unsigned long long m_ui64BackGroundFetchStopTime;
    id m_fetchCompletionHandler;
    _Bool m_isFirstLaunching;
    _Bool m_isInSafeMode;
    MMSMStartViewController *m_safeModeViewController;
    UIWindow *_window;
    id _backgroundSessionCompletionHandler;
    VoIPTokenRetriveObject *_m_voipTokenRetriveObject;
}

- (void)ClearBackGroundFetch;
- (long long)GetAppVerCompareWithLastRun;
- (_Bool)IsChinese;
- (void)LogFeatureExt:(unsigned int)arg1 logExt:(id)arg2 isReportNow:(_Bool)arg3 isImportant:(_Bool)arg4;
- (void)LogFeatureIdKey:(unsigned int)arg1 key:(unsigned int)arg2 value:(unsigned int)arg3 isKeyLog:(_Bool)arg4;
- (void)LogWithinCommon:(int)arg1 module:(const char *)arg2 file:(const char *)arg3 line:(int)arg4 funcName:(const char *)arg5 message:(id)arg6;
- (void)NetworkLogOutput:(id)arg1;
- (void)RenamePath;
- (_Bool)ShouldLog:(int)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)apnsSilentPushTimeOut:(id)arg1;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(id)arg3;
- (void)application:(id)arg1 didChangeStatusBarFrame:(struct CGRect)arg2;
- (void)application:(id)arg1 didChangeStatusBarOrientation:(long long)arg2;
- (void)application:(id)arg1 didFailToContinueUserActivityWithType:(id)arg2 error:(id)arg3;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(id)arg3;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)application:(id)arg1 didRegisterUserNotificationSettings:(id)arg2;
- (void)application:(id)arg1 didUpdateUserActivity:(id)arg2;
- (void)application:(id)arg1 handleActionWithIdentifier:(id)arg2 forLocalNotification:(id)arg3 completionHandler:(id)arg4;
- (void)application:(id)arg1 handleActionWithIdentifier:(id)arg2 forLocalNotification:(id)arg3 withResponseInfo:(id)arg4 completionHandler:(id)arg5;
- (void)application:(id)arg1 handleActionWithIdentifier:(id)arg2 forRemoteNotification:(id)arg3 completionHandler:(id)arg4;
- (void)application:(id)arg1 handleActionWithIdentifier:(id)arg2 forRemoteNotification:(id)arg3 withResponseInfo:(id)arg4 completionHandler:(id)arg5;
- (void)application:(id)arg1 handleEventsForBackgroundURLSession:(id)arg2 completionHandler:(id)arg3;
- (_Bool)application:(id)arg1 handleOpenURL:(id)arg2 bundleID:(id)arg3 annotation:(id)arg4;
- (void)application:(id)arg1 handleWatchKitExtensionRequest:(id)arg2 reply:(id)arg3;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(id)arg3;
- (void)application:(id)arg1 performFetchWithCompletionHandler:(id)arg2;
- (void)application:(id)arg1 willChangeStatusBarFrame:(struct CGRect)arg2;
- (void)application:(id)arg1 willChangeStatusBarOrientation:(long long)arg2 duration:(double)arg3;
- (_Bool)application:(id)arg1 willContinueUserActivityWithType:(id)arg2;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
@property(copy, nonatomic) id backgroundSessionCompletionHandler; // @synthesize backgroundSessionCompletionHandler=_backgroundSessionCompletionHandler;
- (void)beforeMainLauching;
- (void)clearServiceMemory;
- (void)clearServiceObject;
- (void)clearURLCache;
- (void)closeMainFrameInternal;
- (void)closeMainFrameWithoutReset;
- (void)continueMainLaunching:(id)arg1;
- (void)dealloc;
- (id)decodeUrlAttrs:(id)arg1;
- (void)delayStopMain;
- (void)detectAppFirstRunOrFirstRunAfterUpgrade;
- (void)didReceiveLocalMemoryWarning:(id)arg1;
- (void)doSendToken:(id)arg1 error:(_Bool)arg2;
- (void)doSendTokenTimeOut;
- (void)firstStartAfterUpgradeDowngrade;
- (_Bool)getInBackground;
- (double)getMainWindowHeight;
- (double)getMainWindowWidth;
- (void)handleMMSafeModeDidEndNotification:(id)arg1;
- (void)handleMemoryWarning;
- (void)handleOpenPush;
- (_Bool)handleOpenURL:(id)arg1 bundleID:(id)arg2;
- (void)initServiceObject;
- (_Bool)isWeWorkURL:(id)arg1;
- (void)jumpToChatWhenReceivePush:(id)arg1 remotePush:(_Bool)arg2;
- (void)logEssencialInfo;
@property(retain, nonatomic) NSRecursiveLock *mActiveLock; // @synthesize mActiveLock;
@property(nonatomic) _Bool mInBackGroundFetch; // @synthesize mInBackGroundFetch;
@property(readonly, nonatomic) CAppObserverCenter *m_appObserverCenter; // @synthesize m_appObserverCenter;
@property(readonly, nonatomic) CAppViewControllerManager *m_appViewControllerMgr; // @synthesize m_appViewControllerMgr;
@property(readonly, nonatomic) _Bool m_isActive; // @synthesize m_isActive;
@property(retain, nonatomic) CMainControll *m_mainController; // @synthesize m_mainController;
@property(retain, nonatomic) NSString *m_nsSound; // @synthesize m_nsSound;
@property(retain, nonatomic) NSString *m_nsToken; // @synthesize m_nsToken;
@property(retain, nonatomic) NSString *m_nsVoipSound; // @synthesize m_nsVoipSound;
@property(nonatomic) unsigned long long m_ui64BackGroundFetchStopTime; // @synthesize m_ui64BackGroundFetchStopTime;
@property(retain, nonatomic) VoIPTokenRetriveObject *m_voipTokenRetriveObject; // @synthesize m_voipTokenRetriveObject=_m_voipTokenRetriveObject;
- (void)mainThreadMonitorStart;
- (void)mainUISetting;
- (void)monitorResource;
- (void)onUpdateResourceInfo:(id)arg1;
- (void)process3rdAppSupportContentFlagFromOpenUrl:(id *)arg1 andUrlStr:(id *)arg2 appID:(id)arg3;
- (void)registerClsMethodObserver;
- (void)registerLazyExtensionListener;
- (void)releaseSeviceCenter;
- (void)resetBadge;
- (void)saveAppVersion;
- (void)setInBackground:(_Bool)arg1;
- (void)setUserAgent;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void)setupForShortcut;
- (void)setupMMCommonAdapter;
- (_Bool)shouldEnterSafeMode;
- (void)tryProtectLaunchBeforeDeviceFirstUnlock;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

