//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKit.h>
//#import "UIViewController.h"
@protocol IUiUtilExt <NSObject>
@end
@protocol MMUIViewControllerDelegate <NSObject>
@end
@protocol UIGestureRecognizerDelegate <NSObject>
@end
//#import "IUiUtilExt.h"
//#import "MMUIViewControllerDelegate.h"
//#import "UIGestureRecognizerDelegate.h"

@class MMDelegateProxy<UIGestureRecognizerDelegate>, MMLoadingView, MMTitleView, MMUINavigationBar, NSMutableArray, NSMutableDictionary, NSString, UIBarButtonItem, UIColor, UILabel, UINavigationController, UIResponder, UIView;

@interface MMUIViewController : UIViewController <IUiUtilExt, MMUIViewControllerDelegate, UIGestureRecognizerDelegate>
{
    _Bool m_isPopByClickingURL;
    MMLoadingView *m_loadingViewX;
    unsigned int m_uiVcType;
    _Bool m_bKeyboardShowForGesture;
    UILabel *m_newsTitleRecordLabel;
    NSMutableArray *m_fullScreenViews;
    _Bool _isSupportWXGesture;
    _Bool m_bAnimated;
    _Bool m_bIsBeingPoped;
    _Bool m_bInteractivePopEnabled;
    _Bool m_bDisableAdjustInsetAndOffset;
    double lastScreenWidth;
    UINavigationController *m_navigationController;
    MMTitleView *m_baseTitleView;
    NSMutableDictionary *m_dicDeepLink;
    NSMutableDictionary *m_dicContentInsetAutolayout;
    NSMutableDictionary *m_dicTopOffsetAutolayout;
    NSMutableArray *m_arrEndUserOpInfo;
    MMDelegateProxy<UIGestureRecognizerDelegate> *m_interactivePopGestureRecognizerDelegate;
    UIResponder *previousResponder;
    UIBarButtonItem *m_leftBarBtnItem;
    UIBarButtonItem *m_rightBarBtnItem;
    UIColor *m_titleColor;
    MMUINavigationBar *fakeNaviView;
    _Bool m_hasAppear;
    _Bool _m_bAnimating;
    _Bool _m_bStopPopWhenDeleteContact;
    UIView *bottomView;
    UIViewController *_presentingModalViewController;
    UIViewController *_presentedModalViewController;
    unsigned long long _lockedOrientation;
}

- (void)AddViewToFullScreenViewList:(id)arg1;
- (void)ReLayoutFullScreenViews;
- (void)RemoveFullScreenViewList;
- (_Bool)accessibilityPerformEscape;
- (void)addFakeNaviView;
- (void)adjustSubviewRects;
- (void)adjustTableViewInset:(id)arg1;
- (void)adjustTableViewRect;
- (void)adjustView;
- (void)adjustViewAndNavBarRect;
- (void)appendEndOpInfo:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)beginAppearanceTransition:(_Bool)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView;
- (void)changeTopBarsHiddenAnimated:(_Bool)arg1;
- (void)dealloc;
- (void)didAppear;
- (void)didBeginEditing:(id)arg1;
- (void)didDisshow;
- (void)didEndEditing:(id)arg1;
- (void)didMoveToParentViewController:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)disMissSelf;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (double)getContentViewHeight;
- (double)getContentViewY;
- (double)getContentViewYforTranslucentNaviBar;
- (double)getLeftBarButtonWidth;
- (id)getNavigationLeftButton:(id)arg1;
- (id)getNavigationRightButton:(id)arg1;
- (double)getRightBarButtonWidth;
- (double)getSearchBarSearchingY;
- (id)getTitleColor;
- (id)getVCWithDeepLinkName:(id)arg1;
- (id)getViewController;
- (double)getVisibleHeight;
- (double)getVisibleHeightOri:(long long)arg1;
- (void)handleUrl:(id)arg1 DisableFirstGetA8Key:(_Bool)arg2 extraInfo:(id)arg3;
- (id)init;
- (void)initDeepLinkConfig;
- (_Bool)interactivePopGestureRecognizerShouldBegin:(id)arg1;
- (void)internalAddFakeNaviView:(id)arg1;
- (_Bool)isPresentedIn;
- (_Bool)isPushedIn;
- (_Bool)isSubviewResponder:(id)arg1;
@property(nonatomic) _Bool isSupportWXGesture; // @synthesize isSupportWXGesture=_isSupportWXGesture;
- (_Bool)isSvrErrorTipForbidden;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
@property(retain, nonatomic) MMLoadingView *loadingViewX; // @synthesize loadingViewX=m_loadingViewX;
- (void)lockOrientation:(long long)arg1;
@property(nonatomic) unsigned long long lockedOrientation; // @synthesize lockedOrientation=_lockedOrientation;
@property(retain, nonatomic) NSMutableArray *m_arrEndUserOpInfo; // @synthesize m_arrEndUserOpInfo;
@property(nonatomic) _Bool m_bAnimated; // @synthesize m_bAnimated;
@property(nonatomic) _Bool m_bAnimating; // @synthesize m_bAnimating=_m_bAnimating;
@property(nonatomic) _Bool m_bDisableAdjustInsetAndOffset; // @synthesize m_bDisableAdjustInsetAndOffset;
@property(nonatomic) _Bool m_bInteractivePopEnabled; // @synthesize m_bInteractivePopEnabled;
@property(nonatomic) _Bool m_bIsBeingPoped; // @synthesize m_bIsBeingPoped;
@property(nonatomic) _Bool m_bStopPopWhenDeleteContact; // @synthesize m_bStopPopWhenDeleteContact=_m_bStopPopWhenDeleteContact;
@property(retain, nonatomic) NSMutableArray *m_fullScreenViews; // @synthesize m_fullScreenViews;
@property(retain, nonatomic) UILabel *m_newsTitleRecordLabel; // @synthesize m_newsTitleRecordLabel;
@property(nonatomic) unsigned int m_uiVcType; // @synthesize m_uiVcType;
- (id)mmNavigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onMainWindowFrameChanged;
- (void)onTaskBarHiddenChanged:(_Bool)arg1 withAnimation:(long long)arg2;
- (void)onTopBarFrameChanged;
- (void)onTopBarHiddenChanged:(long long)arg1;
- (void)parseDeepLink:(id)arg1 animation:(_Bool)arg2;
- (void)postNotification;
- (long long)preferredInterfaceOrientationForPresentation;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
@property(nonatomic) __weak UIViewController *presentedModalViewController; // @synthesize presentedModalViewController=_presentedModalViewController;
@property(nonatomic) __weak UIViewController *presentingModalViewController; // @synthesize presentingModalViewController=_presentingModalViewController;
@property(nonatomic) __weak UIResponder *previousResponder; // @synthesize previousResponder;
- (void)protectStatusBarFromBeingFuckedByForeGround:(SEL)arg1;
- (void)removeDuplicateBarButton;
- (void)removeFakeNaviView;
- (void)removeNavigationBarBkg;
- (void)reportEndOpInfo;
- (void)resetTableViewOffset:(id)arg1;
- (void)resetViewStatus;
- (void)resignSubviewResponder:(id)arg1;
- (void)restoreNavigationBarBkg;
- (void)safeSetEdgesForExtendedLayout:(unsigned long long)arg1;
- (void)setAutolayoutContentInset:(struct UIEdgeInsets)arg1 forScrollView:(id)arg2;
- (void)setAutolayoutTopOffset:(double)arg1 forView:(id)arg2;
- (void)setBackBarButton;
- (void)setDeepLinkParam:(id)arg1;
- (void)setIsPopByClickingURL;
- (void)setOutLine:(_Bool)arg1;
- (void)setStatusBarFontBlack;
- (void)setStatusBarFontWhite;
- (void)setStatusBarHidden:(_Bool)arg1;
- (void)setStatusBarHidden:(_Bool)arg1 withAnimation:(long long)arg2;
- (void)setSubView:(id)arg1 OutLine:(_Bool)arg2;
- (void)setTitle:(id)arg1;
- (void)setTitleColor:(id)arg1;
- (void)setTitleInterfaceOritation:(long long)arg1;
- (void)setTitleOnly:(id)arg1;
- (void)setTitleView:(id)arg1;
- (void)setTopBarsHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setWCBizAuthTitle:(id)arg1;
- (_Bool)shouldAutorotate;
- (_Bool)shouldEnableKeyboardInteractivePop;
- (_Bool)shouldInteractivePop;
- (void)startBizLoading;
- (void)startForcedRotationToPortrait;
- (void)startLoadingBlocked;
- (void)startLoadingNonBlock;
- (void)startLoadingWithText:(id)arg1;
- (void)stopBizLoading;
- (void)stopLoading;
- (void)stopLoadingWithFailText:(id)arg1;
- (void)stopLoadingWithOKText:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tagForActivePage;
- (id)tagForCurrentPage;
- (void)unlockOrientation;
- (_Bool)useBlackStatusbar;
- (_Bool)useCustomNavibar;
- (_Bool)useTransparentNavibar;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidBeDismissed:(_Bool)arg1;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewDidBePresented:(_Bool)arg1;
- (void)viewDidBePushed:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewDidPop:(_Bool)arg1;
- (void)viewDidPush:(_Bool)arg1;
- (void)viewDidTransitionToNewSize;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillBeDismissed:(_Bool)arg1;
- (void)viewWillBePoped:(_Bool)arg1;
- (void)viewWillBePresented:(_Bool)arg1;
- (void)viewWillBePushed:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillDismiss:(_Bool)arg1;
- (void)viewWillPop:(_Bool)arg1;
- (void)viewWillPresent:(_Bool)arg1;
- (void)viewWillPush:(_Bool)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willAppear;
- (void)willAppearanceTransition;
- (void)willDisappear;
- (void)willDismissAndShow;
- (void)willDisshow;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willShow;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

