//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

@class CMessageWrap, MsgFastBrowseView, NSMutableArray, NSString, UIButton, UIImageView, UILabel;

@interface MsgResourceBrowseViewController : MMUIViewController
{
    NSMutableArray *m_arrMsg;
    MsgFastBrowseView *m_msgFastBrowseView;
    UIImageView *_footerView;
    UIButton *_selectAllButton;
    UIButton *_deleteButton;
    UILabel *_sizeLabel;
    CMessageWrap *m_curMsgWrap;
    NSString *m_nsChatName;
}

- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)dealloc;
- (void)doDeleteData;
- (id)getSelectButtonTitle;
- (void)handleClickAppMessage:(id)arg1;
- (void)handleClickVideoMessage:(id)arg1;
- (void)hanleClickImageMessage:(id)arg1;
- (void)initData;
- (void)initFooterPannelView;
- (void)initNavBar;
- (void)initView;
- (id)initWithMsgWrap:(id)arg1;
@property(retain, nonatomic) CMessageWrap *m_curMsgWrap; // @synthesize m_curMsgWrap;
@property(retain, nonatomic) NSString *m_nsChatName; // @synthesize m_nsChatName;
- (id)messageWrapsForMsgFastBrowseView:(id)arg1;
- (void)msgFastBrowseView:(id)arg1 didChangeCheckMarkTo:(_Bool)arg2 atSection:(unsigned long long)arg3;
- (void)msgFastBrowseView:(id)arg1 didChangeCheckMarkTo:(_Bool)arg2 withMsgInfo:(id)arg3;
- (void)onCancel;
- (void)onDeleteSelectedData:(id)arg1;
- (void)onReloadDataItem;
- (void)onSelecteAll;
- (void)onSquareImgClicked:(id)arg1 withInfo:(id)arg2 withOffset:(unsigned int)arg3;
- (void)previewAppNode:(id)arg1 msgWrap:(id)arg2;
- (void)rebuildSelectedData;
- (void)updateFooterPannelView;
- (void)viewDidLoad;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

