//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SettingUtil : NSObject
{
}

+ (id)GetLocalUsrImg;
+ (id)getBottleLocalUsrName;
+ (id)getCurUsrDisplayName;
+ (id)getCurUsrName;
+ (id)getCurUsrNickname;
+ (long long)getFontSize;
+ (id)getLocalInfo;
+ (id)getLocalUsrName:(unsigned int)arg1;
+ (id)getMainSetting;
+ (id)getMainSettingExt;
+ (id)getUpdateInfo;
+ (_Bool)isAutoDownloadAdSight:(id)arg1;
+ (_Bool)isAutoDownloadSight:(id)arg1;
+ (_Bool)isAutoDownloadSightForExp:(id)arg1;
+ (_Bool)isAutoPlaySight;
+ (_Bool)isBindQQ;
+ (_Bool)isC2CAdSightInFlowControl:(id)arg1;
+ (_Bool)isC2CSightInFlowControl:(id)arg1;
+ (_Bool)isCurUsrHasAliasName;
+ (_Bool)isCurUsrName:(id)arg1;
+ (_Bool)isHasWBlogAccount;
+ (_Bool)isMicroBlogOpen;
+ (_Bool)isNeverAutoPlaySight;
+ (_Bool)isOpenFloatBottle;
+ (_Bool)isOpenGMail;
+ (_Bool)isOpenQQ;
+ (_Bool)isOpenQQMail;
+ (_Bool)isOpenSX;
+ (_Bool)isOpenVoicePrint;
+ (_Bool)isSnsAdSightInFlowControl;
+ (_Bool)isSnsAutoDownloadAdCanvasSight;
+ (_Bool)isSnsSightInFlowControl;
+ (_Bool)isSnsSightInFlowControlByDailyTime;
+ (_Bool)isSnsSightInFlowControlByDatePeriod;
+ (void)loadCurUserInfo:(id)arg1;

@end

