//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CommonMessageViewModel.h"

@class NSMutableArray, NSString, UIFont;

@interface TextMessageViewModel : CommonMessageViewModel
{
    NSMutableArray *m_subViewModels;
    double m_labelWidth;
    NSString *m_contentText;
    NSString *m_contentPatternText;
    double m_contentTextFontLineHeight;
    long long m_parserType;
    struct CGSize m_contentTextSize;
    struct CGSize m_translatedTextSize;
    NSMutableArray *m_contentTextStyles;
    double _translatedLineY;
    double _contentMidY;
}

+ (_Bool)canCreateMessageViewModelWithMessageWrap:(id)arg1;
- (id)accessibilityDescription;
- (struct CGSize)calculateContentTextSize;
- (struct CGSize)calculateTranslatedTextSize;
- (_Bool)canShowTranslateBottomView;
- (_Bool)canShowTranslatedText;
- (id)cellDataForRow:(unsigned long long)arg1;
- (id)cellViewClassName;
@property(nonatomic) double contentMidY; // @synthesize contentMidY=_contentMidY;
- (id)contentPatternText;
@property(readonly, nonatomic) NSString *contentText;
@property(readonly, nonatomic) UIFont *contentTextFont;
@property(readonly, nonatomic) double contentTextFontLineHeight; // @synthesize contentTextFontLineHeight=m_contentTextFontLineHeight;
@property(nonatomic) struct CGSize contentTextSize; // @synthesize contentTextSize=m_contentTextSize;
@property(retain, nonatomic) NSMutableArray *contentTextStyles; // @synthesize contentTextStyles=m_contentTextStyles;
- (id)initWithMessageWrap:(id)arg1 contact:(id)arg2 chatContact:(id)arg3;
- (_Bool)isLongSplitMessage;
@property(readonly, nonatomic) double labelWidth;
- (struct CGSize)measureContentViewSize:(struct CGSize)arg1;
- (long long)numberOfRowsInSection;
@property(readonly, nonatomic) long long parserType;
- (void)resetLayoutCache;
- (void)setHighlighted:(_Bool)arg1;
- (void)setLinkHighlighted:(_Bool)arg1 url:(id)arg2;
@property(nonatomic) double translatedLineY; // @synthesize translatedLineY=_translatedLineY;
@property(nonatomic) struct CGSize translatedTextSize; // @synthesize translatedTextSize=m_translatedTextSize;
- (id)subViewModels;
- (id)translateInfo;
- (void)updateChatContact:(id)arg1;

@end

