//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CommonMessageCellView.h"

@class MMTipsViewController, NSString, RichTextView, TextFloatPreview, TextMessageViewModel, UIButton, UIImageView, WCUIActionSheet;

@interface TextMessageCellView : CommonMessageCellView
{
    RichTextView *m_richTextView;
    UIButton *m_oTranslateStatusButton;
    UIImageView *m_oTranslateLineView;
    MMTipsViewController *m_oTranslateIntroView;
    WCUIActionSheet *m_uiActionSheet;
    TextFloatPreview *m_floatPreview;
}

- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (_Bool)canBeReused;
- (_Bool)canPeek;
- (_Bool)canShowTranslateMenuItem;
- (double)contentViewCenterY;
- (void)dealloc;
- (id)getPreviewLinkForLocation:(struct CGPoint)arg1 inView:(id)arg2;
- (struct CGRect)getPreviewLinkFrameForLocation:(struct CGPoint)arg1 inView:(id)arg2;
- (void)initRichTextView;
- (void)initTranslateLineView;
- (void)initTranslateStatusButton;
- (void)layoutContentView;
- (void)onClickTipsBtn:(unsigned long long)arg1;
- (void)onCopy:(id)arg1;
- (void)onCopyLinkText:(id)arg1;
- (void)onHide;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onLinkHighlighted:(_Bool)arg1 url:(id)arg2;
- (void)onLinkLongPressed:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onLongTouch;
- (void)onPhoneClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onTouchCancel;
- (void)onTouchDownRepeat;
- (void)onTranslateMessageChanged:(id)arg1;
- (void)onTranslateMessageFailed:(id)arg1 errTip:(id)arg2;
- (void)onTranslateMsg:(id)arg1;
- (void)onWindowHide;
- (_Bool)onlyContainsLink;
- (id)operationMenuItems;
- (void)prepareForReuse;
- (struct CGRect)previewingSourceRectForLocation:(struct CGPoint)arg1 inCoordinateView:(id)arg2;
- (void)setHighlighted:(_Bool)arg1;
- (void)setNeedsDisplay;
- (void)setViewModel:(id)arg1;
- (void)translateMsg; // 将内容翻译显示
- (void)triggerLongPressFor3DTouchAtLocation:(struct CGPoint)arg1 inCoordinateView:(id)arg2;
- (void)updateStatus;
- (id)viewControllerToPreviewWithFromController:(id)arg1 forLocation:(struct CGPoint)arg2 inCoordinateView:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) TextMessageViewModel *viewModel; // @dynamic viewModel;

@end

