//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCBaseControlLogic.h"

@class WCBizLoadingView;

@interface WCBizControlLogic : WCBaseControlLogic
{
    WCBizLoadingView *m_loadView;
}

- (void)dealloc;
- (void)initLoadView;
- (void)showLoadingOK:(id)arg1;
- (void)startCommonLoading;
- (void)startLoading;
- (void)startLoadingBlocked;
- (void)startLoadingOnMainWindow;
- (void)startLoadingWithTip:(id)arg1;
- (void)stopCommonLoading;
- (void)stopLoading;
- (void)stopLoadingOnMainWindow;

@end

