//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"
#import "WCCommitViewAnimationDelegate-Protocol.h"

@class CLLocation, ContactsSelectorController, EmoticonBoardView, ImageSelectorController, MMAsset, MMGrowTextView, MMLoadingView, MMTableViewInfo, MMTimer, NSArray, NSMutableArray, NSString, SightDraft, SightIconView, SightView, UIActivityIndicatorView, UIButton, UIImage, UIImageView, UIView, WCDataItem, WCInputController, WCLocationInfo, WCMusicInfo, WCSelectorView, WCTimelinePOIPickerViewController;

@interface WCNewCommitViewController : MMUIViewController
{
    MMTableViewInfo *_tableViewInfo;
    MMGrowTextView *_textView;
    UIView *_headView;
    WCSelectorView *_withImageView;
    WCSelectorView *_withContactView;
    UIButton *_qzoneButton;
    UIButton *_facebookButton;
    UIButton *_twitterButton;
    UIImage *_sightThumbImage;
    UIImageView *_sightThumbImageView;
    UIActivityIndicatorView *_sightLoadingView;
    SightIconView *_progressView;
    ImageSelectorController *_imageSelectorController;
    ContactsSelectorController *_contactsSelectorController;
    WCInputController *_inputController;
    _Bool _bHasInput;
    UIImageView *_inputView;
    UIButton *_expressionButton;
    unsigned int _iInputSection;
    id <WCCommitViewAnimationDelegate> _delegate;
    WCDataItem *_cacheDateItem;
    MMLoadingView *_loadingView;
    MMTimer *_fireTimer;
    WCLocationInfo *_poiInfo;
    WCMusicInfo *_musicInfo;
    _Bool _bNeedRefresh;
    _Bool _bNeedAnimation;
    _Bool _bShowLocation;
    _Bool _bHideAddView;
    unsigned long long _singlePasteTextMaxLength;
    WCTimelinePOIPickerViewController *_poiPickerViewController;
    NSString *_loadingOKStr;
    _Bool m_hasClickDone;
    _Bool m_isUseMMAsset;
    _Bool m_hasConfirmReturn;
    _Bool m_hasICloudImage;
    _Bool m_bFromWCList;
    EmoticonBoardView *m_emoticonBoardView;
    CLLocation *m_imageLocation;
    unsigned long long _type;
    SightDraft *_sightDraft;
    MMAsset *_sightAsset;
    NSArray *_tempSelectContacts;
    NSMutableArray *_m_imageLocationAry;
    SightView *_m_sightFullScreenPreviewView;
}

- (void)GroupTagViewSelectTempContacts:(id)arg1;
- (void)MMGrowTextViewBeginEditing:(id)arg1;
- (void)MMGrowTextViewHeightDidChanged:(id)arg1;
- (void)OnDone;
- (void)OnFacebookBinded;
- (void)OnPostTimeline;
- (void)OnReturn;
- (void)adjustSubviewRects;
- (void)afterProcessSingleImage;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)animationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
@property(nonatomic) _Bool bHideAddView; // @synthesize bHideAddView=_bHideAddView;
@property(nonatomic) _Bool bNeedAnimation; // @synthesize bNeedAnimation=_bNeedAnimation;
@property(nonatomic) _Bool bShowLocation; // @synthesize bShowLocation=_bShowLocation;
- (void)becomeInput;
- (void)beginAnimationStepOne;
- (void)beginAnimationStepTwo;
- (void)beginAnimationStepTwoWithCustomView:(id)arg1;
- (void)bindFacebook;
- (void)bindQQ;
- (void)cancelIcloudActivity;
- (_Bool)checkImageState;
- (void)commonInit;
- (_Bool)couldSelectContacts;
- (void)createSubviews;
- (void)dealloc;
@property(nonatomic, weak)  id <WCCommitViewAnimationDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didCommitText:(id)arg1;
- (void)doExit;
- (void)facebookCheckAccessTokenValidFinished:(_Bool)arg1;
- (void)fbDidLogin;
- (void)fbDidNotLogin;
- (id)getShowAddress;
- (id)getViewController;
- (void)hideInputController;
- (void)imagesUpdated;
- (id)init;
- (void)initEmoticonView;
- (void)initInputController;
- (void)initInputToolView;
- (void)initView;
- (id)initWithImages:(id)arg1 contacts:(id)arg2;
- (id)initWithSightDraft:(id)arg1;
- (void)keyboardDidHide;
- (void)keyboardWillShow;
@property(retain, nonatomic) NSString *loadingOKStr; // @synthesize loadingOKStr=_loadingOKStr;
@property(nonatomic) _Bool m_bFromWCList; // @synthesize m_bFromWCList;
@property(retain, nonatomic) EmoticonBoardView *m_emoticonBoardView; // @synthesize m_emoticonBoardView;
@property(nonatomic) _Bool m_hasConfirmReturn; // @synthesize m_hasConfirmReturn;
@property(nonatomic) _Bool m_hasICloudImage; // @synthesize m_hasICloudImage;
@property(retain, nonatomic) CLLocation *m_imageLocation; // @synthesize m_imageLocation;
@property(retain, nonatomic) NSMutableArray *m_imageLocationAry; // @synthesize m_imageLocationAry=_m_imageLocationAry;
@property(nonatomic) _Bool m_isUseMMAsset; // @synthesize m_isUseMMAsset;
@property(retain, nonatomic) SightView *m_sightFullScreenPreviewView; // @synthesize m_sightFullScreenPreviewView=_m_sightFullScreenPreviewView;
@property(retain, nonatomic) WCMusicInfo *musicInfo; // @synthesize musicInfo=_musicInfo;
- (void)onAssetImageDonwloadProgress:(double)arg1 assetUrl:(id)arg2;
- (void)onAssetImageDonwloadStart:(id)arg1;
- (void)onExpressionButtonClicked:(id)arg1;
- (void)onFacebookClicked:(id)arg1;
- (void)onLoadingShowOK:(id)arg1;
- (void)onLocationCellClicked;
- (void)onPOIPickerFinished:(id)arg1;
- (void)onPrivacyCellClicked;
- (void)onQZoneClicked:(id)arg1;
- (void)onTextView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)onTwitterClicked:(id)arg1;
- (void)onWCPostPrivacyChanged;
- (void)onWithContactCellClicked;
- (id)openOldText;
@property(retain, nonatomic) WCLocationInfo *poiInfo; // @synthesize poiInfo=_poiInfo;
- (void)postNewItemForSight;
- (_Bool)processImage;
- (void)processUploadTask:(id)arg1;
- (void)reloadData;
- (void)reloadExpressionButtonImage:(int)arg1;
- (void)reloadType;
- (void)removeOldText;
- (void)resignInput;
- (void)restoreLastShareOptions;
- (void)saveShareOptions;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
@property(retain, nonatomic) MMAsset *sightAsset; // @synthesize sightAsset=_sightAsset;
@property(retain, nonatomic) SightDraft *sightDraft; // @synthesize sightDraft=_sightDraft;
@property(retain, nonatomic) NSArray *tempSelectContacts; // @synthesize tempSelectContacts=_tempSelectContacts;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (void)shareOptionsCheck;
- (_Bool)shouldJustReturnMMAsset;
- (_Bool)showAddView;
- (void)showLoadingView;
- (void)showPrivacyAlertView;
- (void)textViewTextDidChange;
- (void)touchesBegan_ScrollView:(id)arg1 withEvent:(id)arg2;
- (void)twitterAuthFinished:(int)arg1;
- (void)twitterCheckAccessTokenValidFinished:(int)arg1;
- (void)twitterWillStartOpenSafari;
- (void)updateContentOffset;
- (void)updateImageLocation:(unsigned int *)arg1;
- (void)updateSelectorView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)writeOldText:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

