//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class UIButton, UIImageView, UILabel, UINavigationController, WCDataItem, WCLikeButton;

@interface WCOperateFloatView : UIView
{
    WCDataItem *m_item;
    WCLikeButton *m_likeBtn;
    UIButton *m_commentBtn;
    UIImageView *m_bkgImageView;
    UIImageView *m_lineView;
    UIView *m_clipView;
    UILabel *m_tipLabel;
    UINavigationController *navigationController;
}

- (void)animationDidStop;
- (void)animationDidStopHide;
- (void)hide;
- (id)init;
@property(readonly, nonatomic) UIButton *m_commentBtn; // @synthesize m_commentBtn;
@property(readonly, nonatomic) WCDataItem *m_item; // @synthesize m_item;
@property(readonly, nonatomic) UIButton *m_likeBtn; // @synthesize m_likeBtn;
@property(nonatomic) __weak UINavigationController *navigationController; // @synthesize navigationController;
- (void)onLikeItem:(id)arg1;
- (void)showWithItemData:(id)arg1 tipPoint:(struct CGPoint)arg2;

@end

